const express = require('express')
const router = express.Router()
const userController = require('../Controllers/userController')
const postController = require('../Controllers/postController')
const jwtMiddleware = require('../Middlewares/jwtMiddleWare')
const multerConfig = require('../Middlewares/multerMiddleware')
const LikeController = require('../Controllers/LikeController')
const commentController = require('../Controllers/commentController')

router.post('/register',userController.register)
router.post('/signin',userController.signIn)
router.post('/addRecipe',jwtMiddleware,multerConfig.single('postImage'),postController.addRecipe)
router.put('/Recipe/edit/:pid',jwtMiddleware,multerConfig.single('postImage'),postController.editRecipe)
router.get('/allRecipe',postController.getAllRecipe)
router.get('/home-Recipe',postController.getHomeRecipe)
router.get('/recent-recipe',postController.getRecentRecipe)
router.get('/userRecipe',jwtMiddleware,postController.getUserRecipe)
router.delete('/deleteRecipe/:pid',jwtMiddleware,postController.deleteUserecipe)
router.get('/userRecipeByPid/:pid',jwtMiddleware,postController.getUserRecipeByPid)
router.post('/likepost/:pId',jwtMiddleware,LikeController.toggleLike)
router.get('/getlikes/:pId',jwtMiddleware,LikeController.getLikes)
router.post('/addComment/:pId',jwtMiddleware,commentController.createComment)
router.get('/getPostcomments/:pId',jwtMiddleware,commentController.getPostComments)
router.delete('/deleteComment',jwtMiddleware,commentController.deleteComment)
router.put('/editComment',jwtMiddleware,commentController.editComment)
router.post('/likeComment',jwtMiddleware,commentController.likeComment)
router.delete('/deleteAccount',jwtMiddleware,userController.deleteAccount)
router.put('/editProfile',jwtMiddleware,multerConfig.single('profile'),userController.editUserProfile)
router.get('/getAllUsers',jwtMiddleware,userController.getAllUsers)
router.get('/getAllPosts',jwtMiddleware,postController.getAllPosts)
router.get('/getAllComments',jwtMiddleware,commentController.getAllComments)
router.post('/googleLogin',userController.googleLogin)

module.exports = router